// Generated by https://quicktype.io

import 'dart:convert';

class ProductApi {
  int? id;
  String? title;
  num? price;
  String? description;
  String? category;
  String? image;
  Rating? rating;

  ProductApi({
    this.id,
    this.title,
    this.price,
    this.description,
    this.category,
    this.image,
    this.rating,
  });

  factory ProductApi.fromJson(Map<String, dynamic> data) {
    final ratingData = data['rating'] as Map<String, dynamic>;

    return ProductApi(
        id: data['id'],
        title: data['title'],
        price: data['price'],
        description: data['description'],
        category: data['category'],
        image: data['image'],
        rating: Rating(rate: ratingData['rate'], count: ratingData['count']));
  }
}

class Rating {
  num? rate;
  int? count;

  Rating({
    this.rate,
    this.count,
  });
}

class ProductExtraInfo {
  bool? isFavorite;
  int? off;
  bool? isAvailable;
  int _quantity;

  int get quantity => _quantity;

  set quantity(int newQuantity) {
    if (newQuantity >= 0) _quantity = newQuantity;
  }

  ProductExtraInfo(
      {this.isFavorite, this.off, this.isAvailable, int quantity = 0})
      : _quantity = quantity;
}

class Producto {
  ProductApi productApi;
  ProductExtraInfo extraInfo;

  Producto({
    required this.productApi,
    required this.extraInfo,
  });
}
